---
pipeline:

    generate-post:
        image: 782066560884.dkr.ecr.us-east-2.amazonaws.com/example-applets-ghpage-builder:latest
        commands:
            - bash -c "sudo ln -sf bash /bin/sh && python docs/scripts/site_rehydrate.py --overwrite-files"

    publish:
        image: 782066560884.dkr.ecr.us-east-2.amazonaws.com/example-applets-ghpage-builder:latest
        commands:
            - git config --global user.name "drone-steve" && git config --global user.name "sosazuwa@dnanexus.com"
            - bash -c "source /usr/local/rvm/scripts/rvm && cd docs && bundle install && rake site:publish"

#        when:
#          event: [local]
#          status:  [ failure, success ]