---
pipeline:

    generate-post:
        image: damienblack/example-applets-ghpage-builder:latest
        commands:
            - bash -c "sudo ln -sf bash /bin/sh && python docs/scripts/site_rehydrate.py --overwrite-files"

    generate-static-site:
        image: damienblack/example-applets-ghpage-builder:latest
        commands:
            - bash -c "source /usr/local/rvm/scripts/rvm && cd docs && bundle install && rake site:generate"
            - echo $GITHUB_USERNAME
        secrets: [ github_username, github_password ]

    publish:
        image: plugins/gh-pages
        pages_directory: docs/_site
        secrets: [ github_username, github_password ]

branches: [master, SCI-436-builds]