---
pipeline:

    geenrate-post:
        image: 782066560884.dkr.ecr.us-east-2.amazonaws.com/example-applets-ghpage-builder:latest
        commands:
            - python docs/scripts/site_rehydrate.py --overwrite-files

    publish:
        image: 782066560884.dkr.ecr.us-east-2.amazonaws.com/example-applets-ghpage-builder:latest
        commands:
            - bash -c "source /usr/local/rvm/scripts/rvm && rake site:publish"

#        when:
#          event: [local]
#          status:  [ failure, success ]