---
pipeline:

    generate-post:
        image: damienblack/example-applets-ghpage-builder:latest
        commands:
            - bash -c "sudo ln -sf bash /bin/sh && python docs/scripts/site_rehydrate.py --overwrite-files"

    publish:
        image: damienblack/example-applets-ghpage-builder:latest
        commands:
            - bash -c "source /usr/local/rvm/scripts/rvm && cd docs && bundle install && rake site:publish"

branches: [master, SCI-436-builds]