---
pipeline:

    generate-post:
        image: registry.internal.dnanexus.com/docker-science/example-applets-ghpage-builder:1.0.0
        commands:
            - bash -c "sudo ln -sf bash /bin/sh && python docs/scripts/site_rehydrate.py --overwrite-files"

    generate-static-site:
        image: registry.internal.dnanexus.com/docker-science/example-applets-ghpage-builder:1.0.0
        commands:
            - bash -c "source /usr/local/rvm/scripts/rvm && cd docs && bundle install && rake site:generate"
            - touch docs/_site/.nojekyll  # Prevent gh-pages rendering random _folders instead

    publish:
        image: plugins/gh-pages
        pages_directory: docs/_site
        secrets: [ github_username, github_password ]

branches: [master, tag]
