source 'https://rubygems.org'

gem 'jekyll', '~> 3.7.4'

group :jekyll_plugins do
	gem 'github-pages', ">=192"
	gem 'jekyll-archives'
	gem 'jekyll-sitemap'
	gem 'jekyll-seo-tag'
	gem 'jekyll-feed'
	gem 'jekyll-extract-element', :path => "/Users/sosazuwa/DOGMA/jekyll-extract-element"
end

group :security_specifics do
	gem 'ffi', '~> 1.9.24'
end