source 'https://rubygems.org'

gem 'jekyll', '3.4.3'

group :jekyll_plugins do
	gem 'github-pages'
	gem 'jekyll-archives'
	gem 'jekyll-sitemap'
	gem 'jekyll-seo-tag'
	gem 'jekyll-feed'
	gem 'jekyll-extract-element'
end